services:
   travian:
      build: travian
      container_name: travian
      ports:
         - "83:80"
      volumes:
         - /media/raid/TravianZ/appdata/TravianZ:/var/www/html
      restart: unless-stopped
   mysql:
      image: "mysql:8.0.40-debian"
      container_name: travian-sql
      environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=travian
         - MYSQL_USER=travian
         - MYSQL_PASSWORD=travian
      volumes:
         - /media/raid/TravianZ/appdata/mysql/data:/var/lib/mysql
      restart: unless-stopped
