services:
   travian:
      build: travian
      container_name: travian
      ports:
         - "${PORT}:80"
      volumes:
         - ${TRAVIAN_LOCATION}:/var/www/html
      restart: unless-stopped
   mysql:
      image: "mysql:8.0.40-debian"
      container_name: travian-sql
      environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=travian
         - MYSQL_USER=travian
         - MYSQL_PASSWORD=travian
      volumes:
         - ${DB_LOCATION}:/var/lib/mysql
      restart: unless-stopped
